Repository KNU-HAEDAL/Gongsikdang-FE, pull requests merged in 2025-03, with the labels that each got.

#37 feat(selectcornerpage): fetchInstance 사용해서 api연동 개선
  src/pages/select-corner/ui/SelectCornerPage.jsx
Labels: 📡 API

#52 issue#51 - 마이페이지 수정
  src/pages/mypage/apis/index.js
  src/pages/mypage/apis/name.api.js
  src/pages/mypage/components/my-info/MyInfo.jsx
  src/pages/mypage/components/purchases-list/PurchasesList.jsx
  src/pages/mypage/hooks/index.js
  src/pages/mypage/hooks/useGetName.js
  src/pages/point/ui/PointPage.jsx
  src/pages/point/ui/PointPage.style.js
  src/shared/components/spinner/Spinner.jsx
  src/shared/components/spinner/index.js
Labels: 😡 Bug Fix, ✨ Feature, 📡 API

#69 refactor(payment): 결제 및 재고감소 API 연동 ( 수정)
  src/pages/payment/apis/purchases.api.js
  src/pages/payment/apis/reduce.api.js
  src/pages/payment/ui/PaymentPage.jsx
Labels: 📡 API

#74 feat(reviewwritepage): 리뷰 작성 및 구매한 음식 목록 조회 API 추가(진행중)
  src/pages/review-write/apis/reviewwritepage.api.js
  src/pages/review-write/ui/ReviewWritePage.jsx
  src/pages/review-write/ui/ReviewWritePage.style.js
Labels: 📡 API

#86 feat(review): 리뷰가 없을 때 메시지 표시 및 코드 정리
  src/pages/review-food/ui/ReviewFoodPage.jsx
  src/pages/review-food/ui/ReviewFoodPage.style.js
Labels: 🎨 Design

#100 feat(PointPage,PaymentPage) : 포인트 사용, 포인트 증감 반영
  src/pages/mypage/components/my-point/MyPoint.jsx
  src/pages/payment/apis/point.api.js
  src/pages/payment/apis/purchases.api.js
  src/pages/payment/ui/PaymentPage.jsx
  src/pages/point/apis/point-charge.api.js
  src/pages/point/ui/PointPage.jsx
Labels: 📡 API

#104 fix(,Instance):axios 타임아웃 증가
  src/pages/payment/ui/PaymentPage.jsx
  src/shared/instance/Instance.js
Labels: 😡 Bug Fix

#107 style: (PurchasesList): QR 코드 이미지
  src/pages/mypage/_assets/QR1.png
  src/pages/mypage/_assets/QR2.png
  src/pages/mypage/components/purchases-list/PurchasesList.jsx
  src/pages/mypage/components/purchases-list/PurchasesList.style.js
  src/pages/point/ui/PointPage.jsx
Labels: 🎨 Design

#112 [배포] PWA 확인용 배포
  .gitignore
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/icons/apple-touch-icon-180x180.png
  public/icons/favicon.ico
  public/icons/icon-144x144.png
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/icons/maskable-icon-512x512.png
  public/vite.svg
  src/pages/review-food/apis/reviewfood.api.js
  src/pages/review-food/ui/ReviewFoodPage.jsx
  src/pages/review-write/apis/reviewwritepage.api.js
  src/pages/review-write/ui/ReviewWritePage.jsx
  sw.js
  vite.config.js
Labels: 🚀 Deploy

#113 [배포] pwa 적용
  index.html
Labels: 🚀 Deploy

#115 feat(RegisterPage): 아이디, 닉네임, 유효성 검사
  src/pages/register/ui/RegisterPage.jsx
Labels: ✨ Feature

#118 [배포] 결제 리다이렉트 적용
  .github/workflows/deploy.yml
  src/pages/payment/ui/PaymentPage.jsx
  src/pages/point/ui/PointPage.jsx
  src/pages/register/ui/RegisterPage.jsx
Labels: 🚀 Deploy

#120 feat(PurchasesList, ReviewWritePage): 구매확정 및 리뷰완료 상태 관리 추가
  src/pages/mypage/components/purchases-list/PurchasesList.jsx
  src/pages/review-write/ui/ReviewWritePage.jsx
Labels: ✨ Feature

#126 feat: 오픈그래프 적용
  index.html
Labels: 🚀 Deploy
